server:
  port: 8095
  error:
    include-message: always
local:
  property:
    host:
      ms-bank-account: localhost
      ms-client: localhost
      ms-credits: localhost
      ms-movement: localhost
      ms-loan: localhost
      ms-debit-card: localhost
      ms-currency-type: localhost
spring:
  application:
    name: service-exchange-rate
  config:
    import: optional:configserver:http://ms-config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      currencytypeCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde local